<a href="https://colab.research.google.com/github/deekshdechamma/NLP/blob/main/spam_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Spam Email Detection using Machine Learning Algorithms
个
↓
# Problem Statement
An email service provider receives thousands of emails every day. Many of these emails are spam and should be filtered automatically before reaching users. Develop an NLP-based text classification model to classify SMS messages as Spam or Ham (Not Spam) using different machine learning algorithms. Compare the performance of the models using appropriate evaluation metrics

Dataset: SMS Spam Collection Dataset

https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset

In [ ]:
#Data preprocessing
#BoW, TF-IDF, Word2Vec, GloVe, FastText
#Naive Bayes, SVM, Decision Tree
#Accuracy, Precision, Recall, F1-score, Confusion Matrix

Import Libraries

In [1]:
import pandas as pd
import numpy as np
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Download NLTK Resources
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [12]:
df=pd.read_csv("/content/spam.csv", encoding='latin-1')

In [13]:
df = df[['v1', 'v2']]
df.columns = ['label', 'message']

In [14]:
df['label'] = df['label'].map({'ham': 0, 'spam': 1})

In [15]:
print("dataset shape:", df.shape)

dataset shape: (5572, 2)


In [16]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text=text.lower()
    text=re.sub('[^a-zA-Z]',' ',text)
    words=text.split()
    words=[
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]
    return ' '.join(words)
df['clean_message'] = df['message'].apply(clean_text)

In [17]:
df['clean_message']

,clean_message
0,go jurong point crazy available bugis n great ...
1,ok lar joking wif u oni
2,free entry wkly comp win fa cup final tkts st ...
3,u dun say early hor u c already say
4,nah think go usf life around though
...,...
5567,nd time tried contact u u pound prize claim ea...
5568,b going esplanade fr home
5569,pity mood suggestion
5570,guy bitching acted like interested buying some...


Train Test Split

In [18]:
X = df['clean_message']
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42)

FEATURE EXTRACTION - BAG OF WORDS

In [21]:
print("-------------Bag of Words-------------")
bow = CountVectorizer()
X_train_bow = bow.fit_transform(X_train)
X_test_bow = bow.transform(X_test)

#Naive Bayes
nb = MultinomialNB()
nb.fit(X_train_bow, y_train)
pred_nb = nb.predict(X_test_bow)


print("\nNaive Bayes Results")
print("Accuracy :", accuracy_score(y_test, pred_nb))
print("Precision:", precision_score(y_test, pred_nb))
print("Recall   :", recall_score(y_test, pred_nb))
print("F1 Score :", f1_score(y_test, pred_nb))
print(confusion_matrix(y_test, pred_nb))
print(classification_report(y_test, pred_nb))

-------------Bag of Words-------------

Naive Bayes Results
Accuracy : 0.9820627802690582
Precision: 0.9452054794520548
Recall   : 0.92
F1 Score : 0.9324324324324325
[[957   8]
 [ 12 138]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       965
           1       0.95      0.92      0.93       150

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115



FEATURE EXTRACTION - TF = IDF


In [22]:
print("-------------TFIDF-------------")
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

#Support vector machine
svm = SVC()
svm.fit(X_train_tfidf, y_train)
pred_svm = svm.predict(X_test_tfidf)

print("\nSVM Results")
print("Accuracy :", accuracy_score(y_test, pred_svm))
print("Precision:", precision_score(y_test, pred_svm))
print("Recall   :", recall_score(y_test, pred_svm))
print("F1 Score :", f1_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))
print(classification_report(y_test, pred_svm))

#Decision tree
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train_tfidf, y_train)
pred_dt = dt.predict(X_test_tfidf)

print("\nDecision Tree Results")
print("Accuracy :", accuracy_score(y_test, pred_dt))
print("Precision:", precision_score(y_test, pred_dt))
print("Recall   :", recall_score(y_test, pred_dt))
print("F1 Score :", f1_score(y_test, pred_dt))
print(confusion_matrix(y_test, pred_dt))
print(classification_report(y_test, pred_dt))

-------------TFIDF-------------

SVM Results
Accuracy : 0.97847533632287
Precision: 0.9846153846153847
Recall   : 0.8533333333333334
F1 Score : 0.9142857142857143
[[963   2]
 [ 22 128]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       965
           1       0.98      0.85      0.91       150

    accuracy                           0.98      1115
   macro avg       0.98      0.93      0.95      1115
weighted avg       0.98      0.98      0.98      1115


Decision Tree Results
Accuracy : 0.9641255605381166
Precision: 0.8928571428571429
Recall   : 0.8333333333333334
F1 Score : 0.8620689655172413
[[950  15]
 [ 25 125]]
              precision    recall  f1-score   support

           0       0.97      0.98      0.98       965
           1       0.89      0.83      0.86       150

    accuracy                           0.96      1115
   macro avg       0.93      0.91      0.92      1115
weighted avg       0.96      0.96      0.96      

MODEL COMPARISION

In [24]:
results = pd.DataFrame({
    "Model":["Naive Bayes","Support Vector Machine","Decision Tree"],
    "Accuracy":[
        accuracy_score(y_test,pred_nb),
        accuracy_score(y_test,pred_svm),
        accuracy_score(y_test,pred_dt)
    ],
    "Precision":[
        precision_score(y_test,pred_nb),
        precision_score(y_test,pred_svm),
        precision_score(y_test,pred_dt)
    ],
    "Recall":[
        recall_score(y_test,pred_nb),
        recall_score(y_test,pred_svm),
        recall_score(y_test,pred_dt)
    ],
    "F1 Score":[
        f1_score(y_test,pred_nb),
        f1_score(y_test,pred_svm),
        f1_score(y_test,pred_dt)
    ]
})

print("\n========== MODEL COMPARISON ==========")
print(results)


========== MODEL COMPARISON ==========
                    Model  Accuracy  Precision    Recall  F1 Score
0             Naive Bayes  0.982063   0.945205  0.920000  0.932432
1  Support Vector Machine  0.978475   0.984615  0.853333  0.914286
2           Decision Tree  0.964126   0.892857  0.833333  0.862069


PREDICT NEW MESSAGE

In [23]:
sample = [
    "Congratulations! You have won a free iPhone. Click here to claim your prize."
]

sample = [clean_text(text) for text in sample]

sample_vector = tfidf.transform(sample)

prediction = svm.predict(sample_vector)

print("\n========== SAMPLE PREDICTION ==========")

if prediction[0] == 1:
    print("Message:", sample[0])
    print("Prediction: SPAM")
else:

    print("Prediction: HAM")


========== SAMPLE PREDICTION ==========
Message: congratulation free iphone click claim prize
Prediction: SPAM
